using Devops_C_OO.Demo.Models;
Personnage p1 = new Personnage();
p1.Name = "Dante";
p1.Stats[StatType.Pv] = 20;
p1.Stats[StatType.Force] = 10;
p1.Stats[StatType.Vitesse] = 100;
Personnage p2 = new Personnage();
p2.Stats[StatType.Pv] = 20;
p2.Stats[StatType.Force] = 10;
p2.Name = "Vergil";
p1.Frapper(p2);
Console.WriteLine(p2.Stats[StatType.Pv]);
Console.WriteLine(p1.Name);